# Numpy Assignment Questions

## 1. What is a Python library? Why do we use Python libraries?

In [1]:
'''
### python : A Python library is a collection of pre-written code, that  can import into Python programs to perform common tasks. 
           These libraries encapsulate functions, classes, and modules that offer a range of functionalities, from simple operations to 
           complex processes, making development more efficient and less error-prone.


### Why Do We Use Python Libraries?
# Libraries are optimized for performance, meaning that they can often execute tasks faster and more efficiently than custom code.

# Libraries follow standard practices and are often maintained by experienced developers. This ensures that the code is robust and 
  adheres to best practices.
    
# Libraries provide reusable code, which helps in avoiding the need to write common functions from scratch. This saves time and effort.

# They provide high-level functions and abstractions, simplifying complex tasks. For instance, libraries like pandas make data manipulation
  easier.
  
# Libraries are often tailored for specific purposes. For example, NumPy is great for numerical computations, matplotlib for plotting, 
 and requests for handling HTTP requests.
 
 
### example :
NumPy: For numerical computations.
Pandas: For data manipulation and analysis.
Matplotlib: For plotting and visualization.
Requests: For making HTTP requests.
TensorFlow: For machine learning and deep learning.
Flask/Django: For web development.
SciPy: For scientific and technical computing.

Using these libraries allows developers to leverage the extensive work already done by others, thereby improving productivity and 
ensuring code quality.     '''

'\n### python : A Python library is a collection of pre-written code, that  can import into Python programs to perform common tasks. \n           These libraries encapsulate functions, classes, and modules that offer a range of functionalities, from simple operations to \n           complex processes, making development more efficient and less error-prone.\n\n\n### Why Do We Use Python Libraries?\n# Libraries are optimized for performance, meaning that they can often execute tasks faster and more efficiently than custom code.\n\n# Libraries follow standard practices and are often maintained by experienced developers. This ensures that the code is robust and \n  adheres to best practices.\n    \n# Libraries provide reusable code, which helps in avoiding the need to write common functions from scratch. This saves time and effort.\n\n# They provide high-level functions and abstractions, simplifying complex tasks. For instance, libraries like pandas make data manipulation\n  easier.\n  \n#

## 2. What is the difference between Numpy array and List?

In [2]:
'''
The main difference between a NumPy array and a list in Python lies in their performance, homogeneity, and memory management.
Here are the key differences:

# Performance:
NumPy arrays are faster than lists, especially when performing operations like calculating mean or sum, which are much faster on 
NumPy arrays.

# Homogeneity:
NumPy arrays have strict requirements on the homogeneity of the objects they contain, meaning they can only store elements of the same type.
Lists, on the other hand, can hold elements of varying data types(hytrogenous data), such as integers, floating-point numbers, strings,
boolean values, or dictionaries.

# Memory Management: 
NumPy arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.
Lists, however, store additional information about each element, such as its type and reference count, which can lead to significant 
overhead when dealing with a large number of elements.

# Creation: 
Lists are built-in data structures in Python, while NumPy arrays require importing the NumPy library.
'''

'\nThe main difference between a NumPy array and a list in Python lies in their performance, homogeneity, and memory management.\nHere are the key differences:\n\n# Performance:\nNumPy arrays are faster than lists, especially when performing operations like calculating mean or sum, which are much faster on \nNumPy arrays.\n\n# Homogeneity:\nNumPy arrays have strict requirements on the homogeneity of the objects they contain, meaning they can only store elements of the same type.\nLists, on the other hand, can hold elements of varying data types(hytrogenous data), such as integers, floating-point numbers, strings,\nboolean values, or dictionaries.\n\n# Memory Management: \nNumPy arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.\nLists, however, store additional information about each element, such as its type and reference count, which can lead to significant \noverhead when dealing with a large number of elements.\n\n# Creatio

## 3.Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print("Shape of the array:", arr.shape)
print("Size of the array:",arr.size)
print("Dimension of the array:", arr.ndim)

Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


## 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

first_row = arr[0]

print("First row:",first_row)

First row: [1 2 3 4]


## 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [5]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

required_ele = arr[2][3]

print("\nElement at third row and fourth column:", required_ele)


Element at third row and fourth column: 12


## 6. Write code to extract all odd-indexed  elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

odd_indexed_ele = arr[:,1::2].flatten() #To convert into single dimentional array
    

print("Original array:\n",arr)
print("\nOdd indexed elements:", odd_indexed_ele)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Odd indexed elements: [ 2  4  6  8 10 12]


## 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [7]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print(random_matrix)


[[0.69217986 0.13867649 0.48201604]
 [0.71265898 0.31878467 0.28973361]
 [0.58539753 0.86062164 0.61944293]]


## 8. Describe the difference between np.random.rand and np.random.randn?

In [8]:

## difference between np.random.rand and np.random.randn
'''
1 np.random.rand
 Generates random numbers from a uniform distribution.
 
 The values are uniformly distributed over the interval 0 and 1 .
 
 Typically used when you need random numbers within a specific range with equal probability.'''

# example
import numpy as np
random_numbers = np.random.rand(3, 2)  # Generates a 3x2 array of random numbers from a uniform distribution.
print(random_numbers)

[[0.78476065 0.79392581]
 [0.42891302 0.25092354]
 [0.80340324 0.77845687]]


In [9]:
## np.random.randn
''' 
Generates random numbers from a normal (Gaussian) distribution.
    
Standard normal distribution with a mean of 0 and a standard deviation of 1. This implies that the numbers are distributed in a bell curve 
centered around 0.
    
np.random.randn(d0, d1, ..., dn) where the arguments specify the dimensions of the output array.'''

# example:
import numpy as np
random_numbers = np.random.randn(3, 2)  # Generates a 3x2 array of random numbers from a standard normal distribution.
print(random_numbers)

[[-0.36460039  0.11447119]
 [-0.9495613   0.80118732]
 [ 1.1831438   1.82349104]]


## 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Original array:\n",arr)
print("original dimention:",arr.ndim)

new_arr = np.expand_dims(arr,axis = 1)

print("\nArray with increased dimension:\n",new_arr)
print("Now dimention becomes:",new_arr.ndim)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
original dimention: 2

Array with increased dimension:
 [[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
Now dimention becomes: 3


## 10. How to transpose the following array in NumPy?
  [[1, 2, 3, 4]
  [5, 6, 7, 8],
  [9, 10, 11, 12]]

In [11]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array:\n",arr)
tranposed_arr = arr.T
print("\nTransposed array:\n",arr.T)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11. Consider the following matrix:
### Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
### Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
### Perform the following operation using Python:
1. index wise multiplication
2. matrix multiplication
3. add both matrics
4. subtract matrix B from A
5. divide matrix B by A

In [12]:
import numpy as np
matrix_a = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
matrix_b = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
print("Matrix A:\n",matrix_a)
print("\nMatrix B:\n",matrix_b)


Matrix A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
##1. Index wise multiplication
print("\nIndexwise multiplication:\n",matrix_a * matrix_b)



Indexwise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [14]:
##2. Matrix multiplication
print("\nMatrix multiplication:\n",matrix_a @ matrix_b.T)


Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [15]:
##3. Addition of both the matrix
print("\nAddition of both the matrix:\n",matrix_a + matrix_b)


Addition of both the matrix:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [16]:
##4. Subtraction of matrix B from matrix A
print("\nSubtraction of matrix b from matrix A:\n",matrix_a - matrix_b)



Subtraction of matrix b from matrix A:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
##5. Division of matrix B by A
print("\nDivision of matrix B by matrix A:\n",matrix_b/matrix_a)


Division of matrix B by matrix A:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 12. Which function in Numpy can be used to swap the byte order of an array?

In [18]:
import numpy as np

# Create an array with a specific byte order
original_array = np.array([11,12,123,14], dtype='>i4')  # '>i4' represents big-endian 32-bit integer

# Print the original array
print("Original array:\n", original_array)

# Swap the byte order
swapped_array = original_array.byteswap()

# Print the array after byte swapping
print("\nArray after byte swapping:\n", swapped_array)

Original array:
 [ 11  12 123  14]

Array after byte swapping:
 [ 184549376  201326592 2063597568  234881024]


## 13. What is the significance of the np.linalg.inv function?

In [19]:
'''The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix(with non-zero determinant).
The result of this function is another matrix, known as the inverse matrix, which, when multiplied by the original matrix, 
results in the identity matrix.

For a given square matrix A , if A^-1 is the inverse of A , then the following relationship holds:

A . A^-1 = A^-1 . A = I

where I is the identity matrix.

The significance of np.linalg.inv lies in its applications, such as:

# Solving Linear Systems of Equations:
Given a linear system of equations Ax = B , where A is a coefficient matrix, x is the column vector of variables, and B is the column vector
on the right-hand side, the solution can be found as x = A^-1B.

# Eigenvalue Problems:
In eigenvalue problems, the inverse of a matrix is often used. For a square matrix A and its eigenvector matrix V(columns are eigenvectors),
the inverse A^-1 is used in the relationship V^-1AV = Λ, where ( Λ) is a diagonal matrix of eigenvalues.'''

'The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix(with non-zero determinant).\nThe result of this function is another matrix, known as the inverse matrix, which, when multiplied by the original matrix, \nresults in the identity matrix.\n\nFor a given square matrix A , if A^-1 is the inverse of A , then the following relationship holds:\n\nA . A^-1 = A^-1 . A = I\n\nwhere I is the identity matrix.\n\nThe significance of np.linalg.inv lies in its applications, such as:\n\n# Solving Linear Systems of Equations:\nGiven a linear system of equations Ax = B , where A is a coefficient matrix, x is the column vector of variables, and B is the column vector\non the right-hand side, the solution can be found as x = A^-1B.\n\n# Eigenvalue Problems:\nIn eigenvalue problems, the inverse of a matrix is often used. For a square matrix A and its eigenvector matrix V(columns are eigenvectors),\nthe inverse A^-1 is used in the relationship V^-1AV = Λ,

## 14. What does the np.reshape function do, and how is it used?

In [20]:
'''The np.reshape function in NumPy is used to give a new shape to an array without changing its data. This function is essential
when you need to organize the data in an array into a different shape, which is a common operation in data manipulation and 
preprocessing tasks.'''


import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_array = np.reshape(array, (2, 3))
print("Original Array:")
print(array)
print("Reshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]
Reshaped Array:
[[1 2 3]
 [4 5 6]]


## 15. What is broadcasting in Numpy?

In [21]:
'''Broadcasting in NumPy is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes in a way that 
avoids making unnecessary copies of data. Broadcasting essentially "stretches" the smaller array across the larger array so that they have compatible 
shapes for element-wise operations.'''

# example
# 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 1D array
array_1d = np.array([10, 20, 30])

# Broadcasting the 1D array across the 2D array
result = array_2d + array_1d
print(result)  

[[11 22 33]
 [14 25 36]]
